// <auto-generated />
using System;
using DatePickerHint.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatePickerHint.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250216061342_SeedProgramOfStudy")]
    partial class SeedProgramOfStudy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatePickerHint.Models.ProgramOfStudy", b =>
                {
                    b.Property<string>("ProgramOfStudyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramOfStudyId");

                    b.ToTable("ProgramOfStudies");

                    b.HasData(
                        new
                        {
                            ProgramOfStudyId = "CPA",
                            Name = "Computer Programmer Analyst"
                        },
                        new
                        {
                            ProgramOfStudyId = "BACS",
                            Name = "Bachelor of Applied Computer Science"
                        });
                });

            modelBuilder.Entity("DatePickerHint.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramOfStudyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramOfStudyId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DatePickerHint.Models.Student", b =>
                {
                    b.HasOne("DatePickerHint.Models.ProgramOfStudy", "ProgramOfStudy")
                        .WithMany()
                        .HasForeignKey("ProgramOfStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramOfStudy");
                });
#pragma warning restore 612, 618
        }
    }
}
