// <auto-generated />
using System;
using DatePickerHint.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatePickerHint.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250216073502_NewInitialCreate")]
    partial class NewInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatePickerHint.Models.ProgramOfStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProgramOfStudies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer Programmer (CP)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bachelor of Applied Computer Science (BACS)"
                        });
                });

            modelBuilder.Entity("DatePickerHint.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramOfStudyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramOfStudyId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1971, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bart",
                            GPA = 2.7000000000000002,
                            LastName = "Simpson",
                            ProgramOfStudyId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1973, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lisa",
                            GPA = 4.0,
                            LastName = "Simpson",
                            ProgramOfStudyId = 2
                        });
                });

            modelBuilder.Entity("DatePickerHint.Models.Student", b =>
                {
                    b.HasOne("DatePickerHint.Models.ProgramOfStudy", "ProgramOfStudy")
                        .WithMany()
                        .HasForeignKey("ProgramOfStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramOfStudy");
                });
#pragma warning restore 612, 618
        }
    }
}
